# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9747caa03525597f967e636d65ea9ac2007500d8584df9e7a7139f3c78a4d30be27106c0caa8f99f12462f4c5d5da48ba82259354a8694af202b369e2363282b

test:
  secret_key_base: 13aa19ffa261bac95ac452b4588a46d28633fab40b70e5476160719b5fe8b6f1d4a07b75a7b1543bca62faea741e55e8d69c0d0a8673bc237d614cfc6fb6879c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
